default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

development:
  <<: *default
  database: scaffold_development
  username: scaffold
  password: scaffold

test: &test
  <<: *default
  database: scaffold_test
  username: scaffold
  password: scaffold

production:
  <<: *default
  database: scaffold_production
  username: scaffold
